name: Core
version: 1.0.0
main: com.github.neapovil.core.Core
description: Utility library
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/core
permissions:
  core.broadcast:
    default: op
